libgeojson: geojson Namespace Reference
geojson Namespace Reference
Namespaces
namespace detail
Enumerations
enum class Type {
Point , MultiPoint , LineString , MultiLineString ,
Polygon , MultiPolygon , GeometryCollection , Feature ,
FeatureCollection
}
Functions
const char * TypeName (Type type)
template<Type G>
const char * TypeName ()
nlohmann::json Position (double lon, double lat, double alt)
nlohmann::json Position (double lon, double lat)
nlohmann::json Point (double lon, double lat, double alt)
nlohmann::json Point (double lon, double lat)
template<typename Callable >
nlohmann::json MultiPoint (size_t numPoints, Callable &&getPoint)
template<typename Callable >
nlohmann::json LineString (size_t numPoints, Callable &&getPoint)
template<typename GetLineLength , typename GetPoint >
nlohmann::json MultiLineString (size_t numLineStrings, GetLineLength &&getLineLength, GetPoint &&getPoint)
template<typename GetRingLength , typename GetPoint >
nlohmann::json Polygon (size_t numRings, GetRingLength &&getRingLength, GetPoint &&getPoint)
template<typename GetNumRings , typename GetRingLength , typename GetPoint >
nlohmann::json MultiPolygon (size_t numPolygons, GetNumRings &&getNumRings, GetRingLength &&getRingLength, GetPoint &&getPoint)
template<typename Callable >
nlohmann::json GeometryCollection (size_t numGeometries, Callable &&getGeometry)
nlohmann::json Feature (const nlohmann::json &geometry, const nlohmann::json &properties)
nlohmann::json Feature (const std::string &id, const nlohmann::json &geometry, const nlohmann::json &properties)
template<typename T , typename = typename std::enable_if< std::is_arithmetic<T>::value>::type>
nlohmann::json Feature (T id, const nlohmann::json &geometry, const nlohmann::json &properties)
template<typename Callback >
nlohmann::json FeatureCollection (size_t numFeatures, Callback &&getFeature)
Enumeration Type Documentation
Type
enum class geojson::Type strong
Enumerator
Point
MultiPoint
LineString
MultiLineString
Polygon
MultiPolygon
GeometryCollection
Feature
FeatureCollection
Definition at line 16 of file libgeojson.h.
Function Documentation
Feature() [1/3]
nlohmann::json geojson::Feature (const nlohmann::json & geometry, const nlohmann::json & properties) inline
Returns a Feature object (section 3.2)
Parameters
geometry A GeoJSON object for the geometry
properties A JSON object holding properties for the feature
Returns
A GeoJSON Feature object
Definition at line 664 of file libgeojson.h.
References TypeName().
Feature() [2/3]
nlohmann::json geojson::Feature (const std::string & id, const nlohmann::json & geometry, const nlohmann::json & properties) inline
Returns a Feature object (section 3.2)
Parameters
id The ID of the feature
geometry A GeoJSON object for the geometry
properties A JSON object holding properties for the feature
Returns
A GeoJSON Feature object
Definition at line 679 of file libgeojson.h.
References Feature, and TypeName().
Feature() [3/3]
template<typename T , typename = typename std::enable_if< std::is_arithmetic<T>::value>::type> nlohmann::json geojson::Feature (T id, const nlohmann::json & geometry, const nlohmann::json & properties) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 690 of file libgeojson.h.
References Feature, and TypeName().
FeatureCollection()
template<typename Callback > nlohmann::json geojson::FeatureCollection (size_t numFeatures, Callback && getFeature) inline
Returns a FeatureCollection object (section 3.3)
Parameters
numFeatures The number of features in the collection
getFeature Callback that takes the feature index and gives back the feature.
Returns
A GeoJSON Feature object
Definition at line 706 of file libgeojson.h.
References TypeName().
GeometryCollection()
template<typename Callable > nlohmann::json geojson::GeometryCollection (size_t numGeometries, Callable && getGeometry)
Returns a GeometryCollection object (section 3.1.8)
Template Parameters
Callable A callable of the form nlohmann::json(size_t index)
Parameters
numGeometries The number of geometries
getGeometry A callback that takes the geometry index and returns the geometry object
Returns
A GeometryCollection JSON object
Definition at line 646 of file libgeojson.h.
References TypeName().
LineString()
template<typename Callable > nlohmann::json geojson::LineString (size_t numPoints, Callable && getPoint)
Returns a GeoJSON LineString object (section 3.1.4)
Template Parameters
Callable A callable of the form void(size_t index, double& lon, double& lat, double& alt) or void(size_t index, double& lon, double& lat)
Parameters
numPoints The number of points
getPoint A callback that takes the point index and sets the lat/lon/altitude
Returns
A GeoJSON LineString object
Definition at line 301 of file libgeojson.h.
References geojson::detail::LineStringCoordinates(), and TypeName().
MultiLineString()
template<typename GetLineLength , typename GetPoint > nlohmann::json geojson::MultiLineString (size_t numLineStrings, GetLineLength && getLineLength, GetPoint && getPoint)
Returns a MultiLineString GeoJSON object (section 3.1.5)
Template Parameters
GetLineLength A callable of the form size_t(size_t index)
GetPoint A callable of the form void(size_t lineIndex, size_t pointIndex, double& lon, double& lat, double& alt)
Parameters
numLineStrings The number of lines
getLineLength A callback that takes the line index and returns the length of the line
getPoint A callback that takes the line and point indices and sets the lat/lon/altitude
Returns
A GeoJSON MultiLineString object
Definition at line 380 of file libgeojson.h.
References geojson::detail::MultiLineStringCoordinates(), and TypeName().
MultiPoint()
template<typename Callable > nlohmann::json geojson::MultiPoint (size_t numPoints, Callable && getPoint)
Returns a GeoJSON MultiPoint object (section 3.1.3)
Template Parameters
Callable A callable of the form void(size_t, double&, double&, double&) or void(size_t, double&, double&)
Parameters
numPoints The number of points
getPoint A callback that takes the point index and sets the lat/lon/altitude
Returns
A JSON MultiPoint object
Definition at line 229 of file libgeojson.h.
References geojson::detail::MultiPointCoordinates(), and TypeName().
MultiPolygon()
template<typename GetNumRings , typename GetRingLength , typename GetPoint > nlohmann::json geojson::MultiPolygon (size_t numPolygons, GetNumRings && getNumRings, GetRingLength && getRingLength, GetPoint && getPoint)
Returns a MultiPolygon GeoJSON object (section 3.1.7)
Template Parameters
GetNumRings A callable of the form size_t(size_t index)
GetRingLength A callable of the form size_t(size_t polyIndex, size_t ringIndex)
GetPoint A callable of the form void(size_t polyIndex, size_t ringIndex, size_t pointIndex, double& lon, double& lat, double& alt)
Parameters
numPolygons The number of polygons
getNumRings A callback that takes the polygon index and returns the number of rings
getRingLength A callback that takes the polygon and ring indices and returns the length of the ring
getPoint A callback that takes the polygon, ring and point indices and sets the lat/lon/altitude
Returns
A GeoJSON MultiPolygon object
Definition at line 618 of file libgeojson.h.
References geojson::detail::MultiPolygonCoordinates(), and TypeName().
Point() [1/2]
nlohmann::json geojson::Point (double lon, double lat) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 135 of file libgeojson.h.
References geojson::detail::PointCoordinates(), and TypeName().
Point() [2/2]
nlohmann::json geojson::Point (double lon, double lat, double alt) inline
Returns a GeoJSON Point object (section 3.1.2)
Parameters
lon The longitude in decimal degrees
lat The latitude in decimal degrees
alt The altitude in WGS84 ellipsoidal meters
Returns
A GeoJSON Point object
Definition at line 129 of file libgeojson.h.
References geojson::detail::PointCoordinates(), and TypeName().
Polygon()
template<typename GetRingLength , typename GetPoint > nlohmann::json geojson::Polygon (size_t numRings, GetRingLength && getRingLength, GetPoint && getPoint)
Returns a Polygon GeoJSON object (section 3.1.6)
Template Parameters
GetRingLength A callable of the form size_t(size_t index)
GetPoint A callable of the form void(size_t ringIndex, size_t pointIndex, double& lon, double& lat, double& alt)
Parameters
numRings The number of rings
getRingLength A callback that takes the ring index and returns the length of the ring
getPoint A callback that takes the ring and point indices and sets the lat/lon/altitude
Returns
A GeoJSON Polygon object
Definition at line 522 of file libgeojson.h.
References geojson::detail::PolygonCoordinates(), and TypeName().
Position() [1/2]
nlohmann::json geojson::Position (double lon, double lat) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 89 of file libgeojson.h.
Position() [2/2]
nlohmann::json geojson::Position (double lon, double lat, double alt) inline
Returns a position array (section 3.1.1)
Parameters
lon The longitude in decimal degrees
lat The latitude in decimal degrees
alt The altitude in WGS84 ellipsoidal meters
Returns
A JSON array with the position
Definition at line 84 of file libgeojson.h.
Referenced by geojson::detail::PointCoordinates(), and geojson::detail::PointCoordinates().
TypeName() [1/2]
template<Type G> const char * geojson::TypeName ()
Returns the name of the given geometry type
Template Parameters
G The geometry type
Definition at line 72 of file libgeojson.h.
References TypeName().
Referenced by geojson::detail::CoordinatesObject(), Feature(), Feature(), Feature(), FeatureCollection(), GeometryCollection(), geojson::detail::IsCcw(), geojson::detail::LinearRingCoordinates(), LineString(), geojson::detail::LineStringCoordinates(), MultiLineString(), geojson::detail::MultiLineStringCoordinates(), MultiPoint(), geojson::detail::MultiPointCoordinates(), MultiPolygon(), geojson::detail::MultiPolygonCoordinates(), Point(), Point(), Polygon(), geojson::detail::PolygonCoordinates(), and TypeName().
TypeName() [2/2]
const char * geojson::TypeName (Type type) inline
Returns the name of the given geometry type
Parameters
type The geometry type
Definition at line 32 of file libgeojson.h.
References Feature, FeatureCollection, GeometryCollection, LineString, MultiLineString, MultiPoint, MultiPolygon, Point, and Polygon.