libgeojson: geojson::detail Namespace Reference
geojson::detail Namespace Reference
Classes
struct is_invocable
struct is_invocable_r
Typedefs
template<class F , class... Args>
using invoke_result = std::result_of< F(Args...)>
template<class F , class R , class... Args>
using IsCallbackSignature = typename std::enable_if< std::is_same< typename detail::invoke_result< F, Args... >::type, R >::value, bool >::type
Functions
nlohmann::json PointCoordinates (double lon, double lat, double alt)
nlohmann::json PointCoordinates (double lon, double lat)
template<Type T>
nlohmann::json CoordinatesObject (nlohmann::json &&coords)
template<typename Callable , detail::IsCallbackSignature< Callable, void, size_t, double &, double &, double & > = true>
nlohmann::json MultiPointCoordinates (size_t numPoints, Callable &&getPoint)
template<typename Callable , detail::IsCallbackSignature< Callable, void, size_t, double &, double &, double & > = true>
nlohmann::json LineStringCoordinates (size_t numPoints, Callable &&getPoint)
template<typename GetLineLength , typename GetPoint , detail::IsCallbackSignature< GetPoint, void, size_t, size_t, double &, double &, double & > = true>
nlohmann::json MultiLineStringCoordinates (size_t numLines, GetLineLength &&getLineLength, GetPoint &&getPoint)
bool IsCcw (const nlohmann::json &coords)
template<typename GetPoint >
nlohmann::json LinearRingCoordinates (size_t numPoints, bool ccw, GetPoint &&getPoint)
template<typename GetRingLength , typename GetPoint , detail::IsCallbackSignature< GetPoint, void, size_t, size_t, double &, double &, double & > = true>
nlohmann::json PolygonCoordinates (size_t numRings, GetRingLength &&getRingLength, GetPoint &&getPoint)
template<typename GetNumRings , typename GetRingLength , typename GetPoint , detail::IsCallbackSignature< GetPoint, void, size_t, size_t, size_t, double &, double &, double & > = true>
nlohmann::json MultiPolygonCoordinates (size_t numPolygons, GetNumRings &&getNumRings, GetRingLength &&getRingLength, GetPoint &&getPoint)
Typedef Documentation
invoke_result
template<class F , class... Args> using geojson::detail::invoke_result = typedef std::result_of<F(Args...)>
Definition at line 156 of file libgeojson.h.
IsCallbackSignature
template<class F , class R , class... Args> using geojson::detail::IsCallbackSignature = typedef typename std::enable_if< std::is_same<typename detail::invoke_result<F, Args...>::type, R>::value, bool>::type
Definition at line 173 of file libgeojson.h.
Function Documentation
CoordinatesObject()
template<Type T> nlohmann::json geojson::detail::CoordinatesObject (nlohmann::json && coords) inline
Returns a GeoJSON object, with a "type" and "coordinates" object
Definition at line 115 of file libgeojson.h.
References geojson::TypeName().
IsCcw()
bool geojson::detail::IsCcw (const nlohmann::json & coords) inline
Tests whether the given position array is counter-clockwise
Parameters
coords The position coordinate array to test
Returns
Whether the array is in counter-clockwise order
Definition at line 404 of file libgeojson.h.
References geojson::TypeName().
Referenced by LinearRingCoordinates().
LinearRingCoordinates()
template<typename GetPoint > nlohmann::json geojson::detail::LinearRingCoordinates (size_t numPoints, bool ccw, GetPoint && getPoint)
Gets the coordinates array for a linear ring, ensures the vertices are in CW or CCW order.
Template Parameters
GetPoint Either a 2D or 3D point callback
Parameters
numPoints The number of points in the ring
ccw Whether the ring shoudl be CCW
getPoint 2D or 3D callback
Returns
A JSON array containing the positions in the linear ring
Definition at line 430 of file libgeojson.h.
References IsCcw(), LineStringCoordinates(), and geojson::TypeName().
Referenced by PolygonCoordinates().
LineStringCoordinates()
template<typename Callable , detail::IsCallbackSignature< Callable, void, size_t, double &, double &, double & > = true> nlohmann::json geojson::detail::LineStringCoordinates (size_t numPoints, Callable && getPoint)
Returns the coordinates array of a LineString object (section 3.1.4)
Template Parameters
Callable A callable of the form void(size_t index, double& lon, double& lat, double& alt)
Parameters
numPoints The number of points
getPoint A callback that takes the point index and sets the lat/lon/altitude
Returns
A JSON array that can go into the coordinates property of a LineString object
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 258 of file libgeojson.h.
References PointCoordinates(), and geojson::TypeName().
Referenced by LinearRingCoordinates(), geojson::LineString(), and MultiLineStringCoordinates().
MultiLineStringCoordinates()
template<typename GetLineLength , typename GetPoint , detail::IsCallbackSignature< GetPoint, void, size_t, size_t, double &, double &, double & > = true> nlohmann::json geojson::detail::MultiLineStringCoordinates (size_t numLines, GetLineLength && getLineLength, GetPoint && getPoint)
Returns the coordinates array of a MultiLineString object (section 3.1.5)
Template Parameters
GetLineLength A callable of the form size_t(size_t index)
GetPoint A callable of the form void(size_t lineIndex, size_t pointIndex, double& lon, double& lat, double& alt)
Parameters
numLines The number of lines
getLineLength A callback that takes the line index and returns the length of the line
getPoint A callback that takes the line and point indices and sets the lat/lon/altitude
Returns
A JSON array that can go into the coordinates property of a MultiLineString object
Definition at line 335 of file libgeojson.h.
References LineStringCoordinates(), and geojson::TypeName().
Referenced by geojson::MultiLineString().
MultiPointCoordinates()
template<typename Callable , detail::IsCallbackSignature< Callable, void, size_t, double &, double &, double & > = true> nlohmann::json geojson::detail::MultiPointCoordinates (size_t numPoints, Callable && getPoint)
Returns the coordinates array of a MultiPoint object (section 3.1.3)
Template Parameters
Callable A callable of the form void(size_t index, double& lon, double& lat, double& alt)
Parameters
numPoints The number of points
getPoint A callback that takes the point index and sets the lat/lon/altitude
Returns
A JSON array that can go into the coordinates property of a MultiPoint object
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 192 of file libgeojson.h.
References PointCoordinates(), and geojson::TypeName().
Referenced by geojson::MultiPoint().
MultiPolygonCoordinates()
template<typename GetNumRings , typename GetRingLength , typename GetPoint , detail::IsCallbackSignature< GetPoint, void, size_t, size_t, size_t, double &, double &, double & > = true> nlohmann::json geojson::detail::MultiPolygonCoordinates (size_t numPolygons, GetNumRings && getNumRings, GetRingLength && getRingLength, GetPoint && getPoint)
Returns the coordinates array of a MultiPolygon object (section 3.1.7)
Template Parameters
GetNumRings A callable of the form size_t(size_t index)
GetRingLength A callable of the form size_t(size_t polyIndex, size_t ringIndex)
GetPoint A callable of the form void(size_t polyIndex, size_t ringIndex, size_t pointIndex, double& lon, double& lat, double& alt)
Parameters
numPolygons The number of polygons
getNumRings A callback that takes the polygon index and returns the number of rings
getRingLength A callback that takes the polygon and ring indices and returns the length of the ring
getPoint A callback that takes the polygon, ring and point indices and sets the lat/lon/altitude
Returns
A JSON array that can go into the coordinates property of a MultiPolygon object
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 561 of file libgeojson.h.
References PolygonCoordinates(), and geojson::TypeName().
Referenced by geojson::MultiPolygon().
PointCoordinates() [1/2]
nlohmann::json geojson::detail::PointCoordinates (double lon, double lat) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 109 of file libgeojson.h.
References geojson::Position().
PointCoordinates() [2/2]
nlohmann::json geojson::detail::PointCoordinates (double lon, double lat, double alt) inline
Returns the coordinates array of a Point object (section 3.1.2)
Parameters
lon The longitude in decimal degrees
lat The latitude in decimal degrees
alt The altitude in WGS84 ellipsoidal meters
Returns
A JSON array that can go into the coordinates property of a Point object
Definition at line 104 of file libgeojson.h.
References geojson::Position().
Referenced by LineStringCoordinates(), MultiPointCoordinates(), geojson::Point(), and geojson::Point().
PolygonCoordinates()
template<typename GetRingLength , typename GetPoint , detail::IsCallbackSignature< GetPoint, void, size_t, size_t, double &, double &, double & > = true> nlohmann::json geojson::detail::PolygonCoordinates (size_t numRings, GetRingLength && getRingLength, GetPoint && getPoint)
Returns the coordinates array of a Polygon object (section 3.1.6)
Template Parameters
GetRingLength A callable of the form size_t(size_t index)
GetPoint A callable of the form void(size_t ringIndex, size_t pointIndex, double& lon, double& lat, double& alt)
Parameters
numRings The number of rings
getRingLength A callback that takes the ring index and returns the length of the ring
getPoint A callback that takes the ring and point indices and sets the lat/lon/altitude
Returns
A JSON array that can go into the coordinates property of a Polygon object
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 474 of file libgeojson.h.
References LinearRingCoordinates(), and geojson::TypeName().
Referenced by MultiPolygonCoordinates(), and geojson::Polygon().